export enum OperationTypeEnum {
    ACOPIO = "ACOPIO",
    EMB_HORTOFRUTICOLA = "EMBHORT",
    PORTEO = "PORTEO",
    STACKING = "STACK",
    INSPECCION_USDA = "INSUSDA",
    ALMACENAJE = "ALMAC",
    DIRECTO_DIFERIDO = "SDDD",
    CARGA_MASIVA = "CARGMA",
    CARGA_GENERAL = "CARGEN"

}